version: '3'
volumes:
  db:
services:
  postgres:
    image: postgres:13
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "usmp"
      POSTGRES_USER: "usmp"
      POSTGRES_PASSWORD: "usmp"
    volumes:
      - db:/var/lib/postgresql/data