# Generated by Django 3.0.7 on 2021-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("national_parks", "0002_auto_20210220_0205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationalparks",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
