# Generated by Django 3.0.7 on 2021-02-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("national_parks", "0003_auto_20210220_0213"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nationalparks",
            options={"verbose_name": "National Parks", "verbose_name_plural": "National Parks"},
        ),
    ]
