# Generated by Django 3.0.7 on 2021-02-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("national_parks", "0004_auto_20210220_0400"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nationalparks",
            name="park_id",
        ),
        migrations.RemoveField(
            model_name="nationalparks",
            name="states_id",
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="area_acres",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="area_square_km",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="coordinates_latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="coordinates_longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="date_established",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="visitors",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="nationalparks",
            name="world_heritage_site",
            field=models.BooleanField(default=True),
        ),
    ]
