# Generated by Django 3.0.7 on 2021-02-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_parks', '0005_auto_20210220_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalparks',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
